### ISSUE TITLE
anki add-on "Hanzi Colorizer" doesn't work

### ISSUE THREAD

**Issue by ijgnd** [Connum/hanzivg#1]
This is about the add-on for Anki 2.0 "[Hanzi Colorizer (stroke order diagrams)](https://ankiweb.net/shared/info/752788067)" released on 2018-06-19.

Thanks for sharing it.

I post here because in the repo that's linked from ankiweb([hanzi-colorize](https://github.com/Connum/hanzi-colorize)) doesn't have an issue section.

The add-on from ankiweb doesn't work. 

There seem to be two problems: It seems to load the package "mock" which is not bundled with anki2.0 (or anki 2.1)

There also seems to be a packaging problem: The zip you download doesn't contain any subfolders instead there are many filenames with backslashes. So after downloading the add-on my add-on folder is littered ...

P.S. There's also this general problem: https://anki.tenderapp.com/discussions/announcements/136-sunsetting-anki-20-support

**Comment by Connum** [comment]
Hi there,

I didn't develop that addon and so far I didn't have the time to look into its code much. I'm afraid I can't be of help porting it to anki 2.0 currently!
